/**
 * /api/admin/growth/readiness-check — Phase 6D end-to-end probe.
 *
 * Fires one representative event per asset family (screenshot,
 * image card, blog, video, infographic, carousel) through
 * ingestEvent() and reports back:
 *
 *   {
 *     fired_at,
 *     summary: { screenshot, image_card, blog, video, ... },
 *     content_ids,
 *     errors,
 *     readiness_pct  // 0-100 across asset families
 *   }
 *
 * The actual producer work happens on Railway out-of-band — this
 * endpoint only confirms the events were INGESTED and matched a
 * rule. To verify the asset itself produced, the operator should
 * watch /admin/growth/media for state transitions.
 *
 * Admin-only.
 */
import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { isAdmin }      from '@/lib/admin'
import { ingestEvent }  from '@/lib/growth/automation'

export const dynamic     = 'force-dynamic'
export const runtime     = 'nodejs'
export const maxDuration = 60

interface FamilyResult {
  family:     string
  event_type: string
  outcome:    string
  matched:    number
  content_id: string | null
  error?:     string
}

async function gate() {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: NextResponse.json({ error: 'Unauthorized' }, { status: 401 }) }
  if (!isAdmin(user.email)) return { error: NextResponse.json({ error: 'Forbidden' }, { status: 403 }) }
  return { user }
}

const SAMPLE_EDUCATIONAL = {
  topic:    'Readiness check',
  topic_tag: 'readiness-check',
  headline: 'Readiness probe — composing one of each',
  hook:     'A representative piece per asset family to verify the pipeline end-to-end.',
  concept:  'This blog/educational is auto-generated by /api/admin/growth/readiness-check. It exists so the operator can verify the asset-worker is producing each kind on demand.',
  example:  'Asset families covered: screenshot, image_card, infographic, carousel, blog, video.',
  mistakes: 'Treating this row as marketing content. It is operational.',
  takeaway: 'Check /admin/growth/media for the resulting assets.',
  body:     'This educational was composed by the readiness-check endpoint to verify the asset pipeline. It auto-publishes via the existing rules.',
  reading_min: 1,
  summary:  'Readiness probe — one piece per asset family.',
}

const PROBES: Array<{ family: string; event_type: string; payload: Record<string, unknown> }> = [
  {
    family:     'screenshot',
    event_type: 'showcase.daily',
    payload:    { ...SAMPLE_EDUCATIONAL, target: 'dashboard' },
  },
  {
    family:     'blog',
    event_type: 'educational.blog',
    payload:    SAMPLE_EDUCATIONAL,
  },
  {
    family:     'video',
    event_type: 'video.daily',
    payload:    {
      ...SAMPLE_EDUCATIONAL,
      line_1: SAMPLE_EDUCATIONAL.topic,
      line_2: SAMPLE_EDUCATIONAL.headline,
      line_3: SAMPLE_EDUCATIONAL.concept.split('. ')[0] ?? '',
      line_4: 'Learn more on AlgoSphere Quant.',
    },
  },
  {
    family:     'educational_text',
    event_type: 'manual.fire',
    payload:    SAMPLE_EDUCATIONAL,
  },
]

export async function POST(_req: Request) {
  const g = await gate()
  if ('error' in g) return g.error

  const results: FamilyResult[] = []

  for (const probe of PROBES) {
    try {
      const out = await ingestEvent({
        event_type: probe.event_type,
        source:     'readiness_check',
        payload:    probe.payload,
      })
      results.push({
        family:     probe.family,
        event_type: probe.event_type,
        outcome:    out.outcome,
        matched:    out.matched.length,
        content_id: out.matched.find((m) => m.content_id)?.content_id ?? null,
      })
    } catch (err) {
      results.push({
        family:     probe.family,
        event_type: probe.event_type,
        outcome:    'error',
        matched:    0,
        content_id: null,
        error:      err instanceof Error ? err.message : 'unknown',
      })
    }
  }

  const successful = results.filter((r) => r.outcome === 'ok').length
  const readiness_pct = Math.round(100 * successful / results.length)

  return NextResponse.json({
    fired_at:     new Date().toISOString(),
    fired_by:     g.user.email ?? g.user.id,
    summary: {
      total:      results.length,
      successful,
      readiness_pct,
    },
    results,
    note: 'Producers run out-of-band on Railway. Watch /admin/growth/media for asset_state → ready transitions over the next 1-3 minutes.',
  }, { status: readiness_pct === 100 ? 200 : 207 })
}

export const GET = POST
